### ISSUE TITLE
Can the routes be dynamic? (no crow::black_magic::const_str)

### ISSUE THREAD

**Issue by luxe** [CrowCpp/crow#164]
I'm looking to make my routes configurable- probably loaded from a file.  
Is there a way to make the following work?
```
#include "include/crow.h"
int main()
{
    crow::SimpleApp app;

    std::string route = "/";
    CROW_ROUTE(app, route)([](){
        return "Hello world";
    });

    app.port(18080).multithreaded().run();
}
```

```
error: no viable conversion from 'std::string' (aka 'basic_string<char, char_traits<char>, allocator<char>>') to 'crow::black_magic::const_str'
```

**Comment by The-EDev** [comment]
Officially, Crow can only take rvalues as routes, meaning the value has to be temporary and cannot be a variable.
But basic testing shows that a bit of modification to `app.h` can make what you're trying to do work, specifically changing this:
https://github.com/CrowCpp/crow/blob/408166a06f36b4f6fe7be16ed0e5f2bb4ea9e76e/include/crow/app.h#L78
to this:
```cpp
DynamicRule& route_dynamic(std::string& rule)
```
You can then use `app.route_dynamic(route)` instead of `CROW_ROUTE(app, route)`. Which worked for me.

I should still mention that I'm not aware of what consequences this can have. And that it isn't advised to change routes after app.run() is called..

**Comment by The-EDev** [comment]
I'll look further into this when I have time. I might end up trying an official implementation so that settings can be loaded from a config file (which was one of the goals @ipkn was trying to achieve)

**Comment by The-EDev** [comment]
While I do believe settings coming from a config file would be a good addition, I'm not sure if routes should be a part of that. So I'll close this issue.
