### ISSUE TITLE
How to implement authentication in crow

### ISSUE THREAD

**Issue by adeolaibigbemi** [CrowCpp/Crow#176]
Please am new to crow and c++.
Been trying my hand around crow for some weeks now.

I want to implement authentication in crow, like I want to implement endpoints that will require the client to provide bearer token or username and password.

Does crow have a facility for this? or are there alternative c++ libs for this problem.

**Comment by The-EDev** [comment]
Please take a look at #144, I've been busy and couldn't make a guide but you should be able to implement this stuff yourself pretty easy :) Let me know if you need any help beyond what's described in #144

**Comment by The-EDev** [comment]
@adeolaibigbemi please let me know if you managed to get authentication working so I can close this issue.

**Comment by adeolaibigbemi** [comment]
I've not been able to wrap my head around your example.
My c++ is not very string yet so it might be a bit difficult reading people's code.

Will appreciate if you have any tutorial that can help as per implementing bearer token in c++/crow

**Comment by The-EDev** [comment]
Well the code primarily handles dealing with databases. 
But handling a bearer token boils down to 4 steps:
1. `req.get_header_value("Authorization");` (Get the value in the request headers that says `"Bearer xyzabc123"`).
2. get the part following the space (`xyzabc123`).
3. compare that against what you have stored.
4. return either `true` or `false` based on step 3
To get that to work with crow you you just need to add an `if (verify_token(req))` at the beginning of your route (after the `CROW_ROUTE(app, "/")([](){` and before the `}`)).

Username and password are a little different, steps 1 and 2 are exactly the same (with `Basic` instead of `Bearer`) but then it takes a detour:
3. decode the Base64 string into `username:password` (check [this post](https://stackoverflow.com/questions/180947/base64-decode-snippet-in-c) out for a way to do it, keep in mind the client will do the encoding, you just need to decode)
4. assign everything before the `:` as username and everything after as password, discard the `:`.
5. compare against stored data
6. return either `true` or `false` based on step 5
Getting it to work with crow is exactly the same as with bearer tokens.

I hope this helps.

**Comment by adeolaibigbemi** [comment]
Thanks so much,
This is helpful, with this breakdown explanation I am sure I can implement it myself.

Thanks

**Comment by The-EDev** [comment]
No problem, please feel free to ask if you've got any more questions
