### ISSUE TITLE
common REST patterns

### ISSUE THREAD

**Issue by chromafunk** [CrowCpp/Crow#178]
So, I am a total n00b on all things REST. My program sends data to a processor that prepares the data received in json format, to later be served to a React app. What I would like to know is, what is a common pattern to follow on this situation ? The data is being continuously sent and processed from the origin, so it's kinda of a "real-time" react visualization app. What I thought is to receive the data, and each thread will POST it to a particular route. Then, at the client side ( the React app ) the app is continuously sending GET to a route that returns what was sent on POST.

POST to POST route ----> store data on buffer ---- > React app checks for data via GET ----> empty buffer ?

Thanks !

**Comment by The-EDev** [comment]
REST is primarily designed for being between clients and a database, for something real time (messaging, notifications, or any situation where the server should send data without a request) Websockets might be a better solution. Luckily Crow also supports websockets. There are instructions on getting websockets to work over at https://crowcpp.org . But you'll want to read on getting them to work with react since I've never used it.

**Comment by chromafunk** [comment]
thanks for clarifying, much appreciated. I will go ahead and see how can I hook a simple react websocket app with my crow app. Thanks !

**Comment by The-EDev** [comment]
No problem! Let me know if you have any more questions.
