### ISSUE TITLE
Precompiling crow in some way?

### ISSUE THREAD

**Issue by Iuliean** [CrowCpp/Crow#179]
Sorry if there is something obvious that i am missing but i just started learning more about compiling stuff myself

I am writing a small app for a raspberry pi zero W (it is the weakest pi possible i think it has 1 core :( ) and crow takes A LOT of time to compile since it has to compile the things it imports from boost.

Is there a way to precompile it ? I tried making it a precompiled headder but then the compiler started yelling at me that i did not define `CROW_MAIN` and i am doubting it will work if i set it as a compiler define.

How can i compile it as a lib file (if possible) ?

**Comment by The-EDev** [comment]
AFAIK crow was a compiled library around 2014.. But I'm not sure with all the changes made since then compiling it is still possible (without many changes at least). What I do is I write my program on my workstation, then run a virtual machine with the same hardware as my target hardware (in my case it was a debian 10 AMD64 device) and compile the code there.

**Comment by Iuliean** [comment]
thanks that's actually a very good suggestion i'll see if i can emulate the pi on my workstation. you might have saved me a lot of compilation time :)

**Comment by The-EDev** [comment]
Best of luck. Let me know if you need any more help.

**Comment by The-EDev** [comment]
I don't think this will be implemented.. If anyone thinks this is important enough let me know so I can reopen it and we can continue the discussion
