### ISSUE TITLE
SIGINT and SIGTERM Handeling

### ISSUE THREAD

**Issue by JakeInit** [CrowCpp/Crow#187]
In my application I use a signal handler to allow for stopping the application cleanly when users want to suddenly abort. It looks like your signal handler was overwriting what I had written and was causing "unexpected" behavior in my application. To fix for my application, I went into catch.hpp, app.h, and http_server.h and removed the instances of SIGINT and SIGTERM. My application solely runs on Ubuntu 18.04.

I bring this to your attention in case you feel there is a better way to handle this scenario. Your application is still doing what I need and I do not have any actual issues. Thanks for the easy and great server application.

**Comment by The-EDev** [comment]
Thanks for opening the issue @JakeInit. There is in fact a better way to handle this.

All crow really does is call `app.stop()` when it receives either signal, so all you need to do is call `app.signal_clear()` and stop the app through your own handler.

I hope this helps and please let me know if your issue is fixed and if you need more help.

**Comment by JakeInit** [comment]
Ah yes. I see where the signal_ vector gets emptied when calling this. This is a much better solution so I do not need to manually make the change on new machines. Thanks,

**Comment by The-EDev** [comment]
No problem, I'll close this issue now.
