### ISSUE TITLE
HTTP Status Codes

### ISSUE THREAD

**Issue by Leon0402** [CrowCpp/Crow#220]
Hi, 

I would appreciate some defined constants for the http status codes. I couldn't find any.

**Comment by The-EDev** [comment]
Could you please elaborate?

**Comment by Leon0402** [comment]
HTTP Status codes like HTTP_OK or HTTP_CREATED. So you don't have to define them yourself or use magic numbers in the code. 

For instance: https://github.com/whoshuu/cpr/blob/63bfcc6292bba06f9806994ee5474baadff48254/include/cpr/status_codes.h

Or: https://github.com/pistacheio/pistache/blob/eb2aa7f2b611f421c0bfed6eff0ad5720f21eb42/include/pistache/http_defs.h#L36

So you can write: `row::response { Status::HTTP_OK };` instead of `row::response { 200 };`. Currently clang tidy says "No magic numbers". So I define my own constants. 
But this seemed like something general useful, which other libraries provide as well, so I feel like it should be part of the library and not defined by me.

**Comment by The-EDev** [comment]
hmmm, I don't see a circumstance where I would use something like that, but I can understand providing an option. Maybe using macros like `CROW_STATUS_OK`

**Comment by Leon0402** [comment]
Really? You prefer magic values like "411"? Instead of something like "HTTP_LENGTH_REQUIRED". I mean unless you learned all status code, I personally find it much easier to read the message instead of the code. 

I think I would prefer `constexpr` instead of macros. I don't see any reason, why using macros here would be necessary. 
Regarding the name, it should probably be in the crow namespace and then would be: 

`crow::STATUS_OK` or `crow::HTTP_OK` or `crow::OK` or `crow::status::OK` or `crow::http::ok`. 
I think my favourity would be  `crow::status::OK` and my second favourite `crow::HTTP_OK`.

**Comment by The-EDev** [comment]
IMO HTTP status codes are widely known and standardized. And I personally don't like when too much is obfuscated from me (sometimes it reaches a level where I can't do what I want because the things I need are abstracted away).

The problem with `constexpr` for Crow is that you need a macro (`CROW_MAIN`) to define them anyway, that's why I suggested using macros. A third option would be to use an enum with the corresponding codes, still uses `crow::status::OK` but doesn't necessarily need the `CROW_MAIN` mess

**Comment by Leon0402** [comment]
> IMO HTTP status codes are widely known and standardized. And I personally don't like when too much is obfuscated from me (sometimes it reaches a level where I can't do what I want because the things I need are abstracted away).

They are for sure, although I personally don't know all of them :-) Just the more common ones. I see your point though.  


> The problem with `constexpr` for Crow is that you need a macro (`CROW_MAIN`) to define them anyway, that's why I suggested using macros

I don't understand? What does these constants have to do with the rest? Why cannot be something like https://github.com/whoshuu/cpr/blob/63bfcc6292bba06f9806994ee5474baadff48254/include/cpr/status_codes.h used? 
Just a simple header with all constexpr status codes, independent of everything else?

**Comment by The-EDev** [comment]
if you have crow defined in more than 1 source file you get multiple definitions of the constexpr

**Comment by Leon0402** [comment]
TBH I still don't understand the issue here. I think I would need some more explanation to actually understand the issue here. But I don't have to, if you're busy. You probably know what you're talking about :-) 
I'm also fine with macros.

**Comment by The-EDev** [comment]
Because Crow is header only, the definition of constant values happen inside the `.cpp` files that include it. The problem occurs when 2 different source files include the same header, now you have the same constant expression defined in 2 different places, and the linker doesn't know which one to link to. I think using an enum would be best here since it doesn't have the same problem as consts but the advantage of being immediately parsed similar to a direct integer code.

**Comment by Leon0402** [comment]
But it's constexpr? This implies static, so there is no linker error. In the worst case, memory is allocated twice in case of an object. But with ints there is no problem at all, it will just be replaced. 

For C++17 it's even better, constexpr then also implies inline so even in case of objects, there will be just once instance.

**Comment by The-EDev** [comment]
> But it's constexpr? This implies static, so there is no linker error.

Well this is embarrassing, I need to look into this more. Thanks a lot for pointing this out

**Comment by Leon0402** [comment]
No worries :-) It is a little bit confusing, especially when the behaviour is changed based on the C++ Standard and is different depending on if you have trivial types or objects.
