### ISSUE TITLE
Example using Crow with Google Charts?

### ISSUE THREAD

**Issue by arnholm** [CrowCpp/Crow#310]
Thank you for your excellent work! I have run your Hello World example successfully.

I would like to use Crow to plot XY-plots of sensor data in a web browser, i.e. time series. I have C++ libraries to access the data.

I see 2 possibilities. Either produce a PNG image on the server and show it in the browser, or better pass the time series data to the client side and plot it using Google Charts. My question is whether an example exists showing a Crow application returning data to Google Charts?

**Comment by The-EDev** [comment]
Hello @arnholm and Thank you for the kind words!

Looking at a [quick overview](https://www.tutorialspoint.com/googlecharts/googlecharts_quick_guide.htm) of google charts, it seems to use HTML and simple JS to display the chart. Which means you could create a [Mustache](http://mustache.github.io/mustache.1.html) template and [render](https://crowcpp.org/guides/templating/) it using the data you have.

There isn't an existing example doing that exactly, but following the guides I linked you should be able to make it without issue.

Let me know if you run into any problems or have any questions. I'd be happy to help.

**Comment by arnholm** [comment]
Ok, many thanks for the quick response and links! I may try the Mustache approach as suggested, I think I understand the concept more or less, I have briefly used similar with Flask, but I haven't used Google Charts yet. It will take me some time but now I have some pointers. I'll try it first and then ask again if I run into problems. Crow seems very interesting.

**Comment by arnholm** [comment]
I have now managed to create a simple weather station web app based on Crow and Google Charts, it is very promising. It works, but I had some problems relating to Mustache and 2d-arrays and also how to get <form> parameters. Would you prefer I bring those up here or should I create new issues for each problem I saw?

**Comment by The-EDev** [comment]
I would prefer if you put them all here, it would make it easier if we need to modify documentation to not go through too many pages.

**Comment by arnholm** [comment]
Ok, all good. In short what I did was to experiment with a weather station app, implementing it first in Flask/Matplotlib and then using Crow/Google Charts. In both cases the same C++ back end code was used. My code is [here](https://github.com/arnholm/wsweb) , the wsweb folder contains the Crow code ( [main.cpp](https://github.com/arnholm/wsweb/blob/master/wsweb/main.cpp) ) and the wsapi_plot folder contains the more or less equivalent Flask code (  [app.py](https://github.com/arnholm/wsweb/blob/master/wsapi_plot/app.py) ). Both have a templates subfolder with index.html.

There were 2 main things I struggled with
- One relating to Mustache and passing parameters, plus Mustache  syntax in general
- One relating to unpacking parameters in C++ from a form on a submit call

**Mustache & passing 2d arrays**

I could not figure out how to transfer 2d arrays in Crow to the page, so I had to transfer them as individual vectors and then reassemble in Javascript. Google Charts require a 2d array for what I did. So my question on this topic is whether this is a limitation of the implementation of Mustache that Crow is using or whether there is something I have overlooked?  If I wanted to draw several curves it seems much easier if all the data could be transferred as one matrix.

**Mustache syntax in HTML different from Flask**

I saw something similar with the form that contained a 'select' control for my various sensors. I wanted to transfer an internal name and a "user name" for it, but this could only be done as 2 different vectors. but in Flask I could do it with a list of tuples. I tried vectors of vectors, but it didn't work in Crow. Also I could not figure out how to set the 'selected' option in Crow Mustache code as I could with Python.

I have not used Mustache before, so I was surprised to see that the Mustache code I used with Python didn't work with Crow
[Mustache code with Python/Flask](https://github.com/arnholm/wsweb/blob/master/wsapi_plot/templates/index.html)

With Crow I had to use a more bare-bone syntax, and compensate with Javascript instead
[Mustache code with Crow](https://github.com/arnholm/wsweb/blob/master/wsweb/templates/index.html)

Does this mean that Mustache in Crow is limited, or the Python Mustache syntax is somehow non-standard? Is there a better way to do what I did?

**Unpacking parameters from a HTML form**

This was fairly straightforward in Flask (see app.py), but I could not find a direct way to do it in Crow, so I ended up writing a C++ helper class  [multipart_params](https://github.com/arnholm/wsweb/blob/master/wsweb/multipart_params.h) , which allowed me to use similar syntax in the Crow app (see main.cpp). Would it be an idea to incorporate this functionality into crow::multipart::message, or have I missed something already there? Feel free to use my code as you find it useful, so that the syntax for extracting parameter values becomes natural in Crow as it is in Flask.

I attach a screenshot of my Crow app
![image](https://user-images.githubusercontent.com/3944480/147884841-e2ed7045-f3e8-49f6-bbaa-3a69ac48b5cd.png)

All in all I am enthusiastic about Crow, and find it much preferable over Flask, but maybe some usability issues could be added.

**Comment by The-EDev** [comment]
I'm still going through everything but one thing I want to point out right away is the difference you noticed between Crow and Flask relating to templates.
The reason is that Flask doesn't use Mustache, it uses a different templating library named [Jinja](https://jinja.palletsprojects.com). One very important difference is that Mustache is logic-less, meaning you cannot put statements like `if` or `while` inside the template itself, instead relying on the context to supply lists and boolean values.

I'll go over the other issues and see what I can do.

**Comment by arnholm** [comment]
Thank you for clearing up the Mustache vs. Jinja confusion, my bad. That makes sense now.  Still, the issue remains how to best do it with Mustache when you have a variable number of curves to pass to something like Google Charts.  I will await your other comments.

**Comment by The-EDev** [comment]
I apologize for taking so long to respond. Here's what I found out:

To begin I saw you using the term "2D Arrays", which for this use case wouldn't be applicable, a 2D array would be an array containing arrays of something. For a line chart all you need is 2 arrays representing 2 axis.

Using JavaScript while completely valid, it kind of negates the idea of "*Logic-less Templates*" and takes the scope of a template from "*Display data*" to "*Process and Display data*" which can be problematic. Fortunately, JavaScript can be completely replaced with a bit of C++ code and Mustache (with the exception of the code creating the Google Chart).

As described [here](https://crowcpp.org/guides/templating/#context). Mustache uses JSON data as for context, meaning you can use JSON Objects, which are far more powerful than lists, tuples, or maps.
With that being said, Instead of taking `x` and `y` and combining them in JS, you could simply put the 2 values in an object and make a list of JSON objects. Then you can iterate on that list using a simple *Mustache section* and use the names of the values for your X and Y axis when creating the chart.

You can also replace the `select` script with JSON objects containing a name, description, and a boolean for whether or not the item is selected in the context and pass those to the template.

I've included an example I made with these solutions applied:
`main.cpp`
```cpp
#include <vector>
#include <string>
#include "crow_all.h"

int main()
{
    std::vector<time_t> x = {1065541611, 1458900112, 977791462, 1279463854, 1383338391, 1095125962};
    std::vector<double> y = {5.6, 123.5, 56.1, 12.8};
    const std::unordered_map<std::string, std::string> sensor_map{{"abc", "xyz"}, {"def", "uvw"}, {"ghi", "rst"}};
    std::string selected = "def";

    crow::SimpleApp app;

    CROW_ROUTE(app, "/")
    (
      [&]()
      {
          auto page = crow::mustache::load("index.html");
          crow::mustache::context ctx;


          // Create list of x y data
          size_t list_length = x.size() > y.size() ? y.size() : x.size();
          std::vector<crow::mustache::context> list;
          for (size_t i = 0; i < list_length; i++)
          {
              crow::mustache::context item;
              item["x"] = x[i];
              item["y"] = y[i];
              list.emplace_back(item);
          }

          ctx["list"] = std::move(list);


          // Create list of sensor data
          std::vector<crow::mustache::context> sensor_list;
          for (auto& sensor : sensor_map)
          {
              crow::mustache::context item;
              item["name"] = sensor.first;
              item["desc"] = sensor.second;
              item["selected"] = sensor.first == selected;
              sensor_list.emplace_back(item);
          }

          ctx["sensors"] = std::move(sensor_list);

          return crow::response(200, "html", page.render(ctx));
      });

    app.port(18080).run();
    return 0;
}
```

`index.html`
```mustache
{{#list}}x is {{x}} and y is {{y}}<br>{{/list}}

<select name="sensor" id="sensor">
  {{#sensors}}
     <option value="{{name}}" {{#selected}} selected {{/selected}}>{{desc}}</option>
  {{/sensors}}
</select>
```

As for the DateTime formatting, you can absolutely format that in C++ instead of JS as well, I just didn't do it in this example, it would probably involve [this question I found](https://codereview.stackexchange.com/questions/150548/time-t-to-string).

---

Moving on to `multipart_params`, I was initially confused since Crow absolutely supported *multipart header parameters*. Going through the code I realized that you actually meant `multipart/form-data` parts, which made a lot more sense.

You are correct in that Crow's implementation of `multipart` messages doesn't go beyond turning the message into proper C++ data structures. And does require knowledge of how a multipart message is structured to work properly.

All of this means that it doesn't support `form-data`, but rather the underlying encoding, which makes your helper class a welcome addition. Though noticing a few optimization problems and potential bugs for general workloads, I'll have to make quite a few modifications before integrating it into Crow. Please don't take this as a slight against your work, it is still very much appreciated and will absolutely help Crow move forward.

---

Another thing I noticed that wasn't exactly related to your questions is that `page.render()` returns a simple string and when used with a `CROW_ROUTE`'s return, it will not properly set the `Content-Type` header to `text/html`. It would probably be worth adding 2 rendering methods, one that returns a string and another that returns a `crow::returnable` object.

It would be best to create 2 new issues, one relating to `form-data` and another relating to `page.render()`.

---

I would like to Thank you very much for your work. You've provided excellent insight into a real life use case, potential integration with other tools, and new features and bugs. I cannot emphasize how important this information is to Crow's development and growth.

Please let me know of any further questions you have and I'll do my best to help.

**Comment by arnholm** [comment]
Fantastic reply, No need to apologize. I am really grateful for such a detailed explanation complete with code! I will have to spend some time digesting your solutions and I will update my code based on your suggestions. Once it is done I'll drop a comment here to give to give you an update.

On the question of 2d Arrays. If the line chart is to contain more than one curve, you need more than 2 arrays. But I believe you have provided the best solution in your example using std::vector<crow::mustache::context> as you can insert many named curves there. This is the kind of thing I was looking for, so thank you!

Please feel free to do whatever you feel is needed with the code I provided (or rewrite it from scratch), the main thing is that Crow ends up supporting extraction of parameters from form data in an easy and intuitive manner.

A quick comment on formatting DateTime in C++. If the time series is long (many thousands) it adds a lot of processing both in C++ to format to e.g.  [ISO8601](https://www.iso.org/iso-8601-date-and-time-format.html) strings and then parse it in JS, plus the bandwidth is greater than just sending the Unix time_t values. If you have to do some JS anyway (which you must with Google Charts), then there is not much to gain. But I do understand your intention of removing JS where possible.

Please excuse my short reply here, I will open the 2 issues as you suggest.

**Comment by arnholm** [comment]
I am trying to implement your code suggestions, but I get this exception immediately and I am not sure I understand why or what it means: 
`(2022-01-05 18:33:34) [ERROR   ] An uncaught exception occurred: not implemented tag type6`

I have cloned the master branch, should I use something else?

**Comment by The-EDev** [comment]
What this error means is that you're passing a tag `{{value}}` with `value` being of type `Object` (which is a JSON object), if you're using a direct tag (not a section), it should be either a number, a string, or a function. I can't help further than this since I don't know the specific code that's causing this issue.

**Comment by arnholm** [comment]
Ok, thanks. After some strange issues I didn't quite understand, I changed some names and things started to work. :-)

My much reduced  [HTML template](https://github.com/arnholm/wsweb/blob/master/wsweb/templates/index.html) . As can be seen, the JS for updating the sensor list form is removed and replaced with Mustache code they way you suggested. I had problems before I renamed the list from `sensors` to `sensor_list` (obviously in both HTML and C++), but it wasn't repeatable afterwards so I must have made some other 'stupid' mistake. Anyway, that part works fine now.

The second improvement in that code is in the `drawBasic()` JS function to draw the chart, where the 2D JS array is built directly as you suggested, everything becomes much shorter and more concise.  The `{{#list}}x is {{x}} and y is {{y}}<br>{{/list}}` part got me fooled for a while...I took it literally until it dawned on me how to do it.

I did not transfer ISO8601 time strings because I find time_t more concise, faster and easier. The JS code there is now quite minimal, and it works.

My updated  [main.cpp](https://github.com/arnholm/wsweb/blob/master/wsweb/main.cpp) implements the scheme you suggested, I just changed some of the naming. This is to me now a useful example. The fact that you can return variables of type `std::vector<crow::mustache::context>` was something I had not figured out by myself. But it does make sense now and it opens up the possibility for things like drawing multiple curves in the same graph.

I am extremely grateful for the patience and detailed support you have provided on this, It has been a great learning experience so far!

**Comment by The-EDev** [comment]
No problem, I'm happy everything is working now.

I'll close this issue, if you have any more questions regarding Google Charts let me know and I'll reopen it.
