### ISSUE TITLE
crow::websocket::connection unique client identifier e.g. port?

### ISSUE THREAD

**Issue by michl2310** [CrowCpp/Crow#319]
Hi,

regarding crow::websocket::connection : 
Is it somehow possible to identify one connection with a unique identifier other than the memory address of the object e.g. the client's port?

Example:
One WS-Crow-server and n clients. All clients connect from the same IP but from differents softwares (web/java/c++).
Now I can check the IP of the connections but not e.g. the port. I cannot identify whether it is the first, second ... connection.

**Comment by The-EDev** [comment]
Hello,

As far as I know, the ports used by a client tend to be random, meaning one client can connect through more than one port.
So if your goal is to identify different connections, then the memory address would be as good an indicator as the request port.
Otherwise if your goal is to identify the client program that made the request, using the `User-Agent` header would be a much better bet at determining which client made the request.

**Comment by michl2310** [comment]
Thank you for your quick response. I will check the User-Agent.
