### ISSUE TITLE
crow::mustache and HTML template file

### ISSUE THREAD

**Issue by arnholm** [CrowCpp/Crow#323]
I am running my crow application under Kubuntu 20.04 and created a .deb file for it with the intention to install it to /usr/local/bin on a different machine than the development machine. 

I also created a .service file and intended to start the application as a systemd service as explained in the crow documentation. But when I started the service it didn't work because there was no 'templates' directory in the current directory and thus no index.html, I had forgotten about that aspect.

Reading the documentation again it says about the crow::mustache HTML template _"It needs to be placed in the templates directory which should be directly inside the current working directory of the crow executable"_.

This seems a bit inconvenient in the above scenario, since the template becomes separated from the application. I wonder what the best practice is for something like this?

For example: Is there a way to compile the HTML template into the application and thus remove the dependency of an external templates directory & file at runtime? Or what is the proper approach to this?

**Comment by The-EDev** [comment]
There are 3 ways to approach this issue,

First, the "_current working directory_" does not need to be the same directory as your Crow executable. you can set it via the `WorkingDirectory` parameter in your `.service` file (go [here](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#) for more information).

Second approach would be to set an absolute path for the templates using `crow::mustache::set_base("/my/new/path")`. This function is undocumented (I apologize about that), and I just noticed it doesn't sanitize the directory, which might be a problem (just leaving a note for myself to fix it).

Last way is as you suggested, placing the templates into strings and using `crow::mustache::compile(template_string)` to create a template rather than loading a file. Though I wouldn't advise this since it means any changes to the template will now require recompiling some or all of your application.

It seems that more documentation on Mustache is needed, I apologize for that and will hopefully get on it soon.

**Comment by arnholm** [comment]
Thanks! I was aware of the first option. The second is nice to know.  Loading the template into a string in a header file and calling `crow::mustache::compile(template_string)`  worked fine when the string was saved as a hex code array. Yes I realize this implies application recompilation when the template changes, but that is ok since I mostly change the application anyway.  I wrote a template-to-header file utility that runs as a pre-build step and checks for file dates in my IDE (Code::Blocks) so it is automatic and only regenerates the header when the template is modified. Then the deployment to another machine becomes super easy, and that is what I wanted now. So thanks for the reply & help!
