### ISSUE TITLE
Implement lambdas in mustache.h

### ISSUE THREAD

**Issue by mrozigor** [CrowCpp/Crow#36]
Lambdas are optional element in mustache spec. Currently not implemented at all.

**Comment by The-EDev** [comment]
Looking at the [spec](https://github.com/mustache/spec/blob/master/specs/%7Elambdas.yml), I've made a few conclusions:
1. lambdas are for the most part pure code
2. They were designed with interpreted languages in mind
3. No current C++ implementation of mustache seems to have support for dynamically loading a lambda from a file (they have to be defined in code)
4. Lambdas defined in code can easily be replaced with function calls

**Comment by The-EDev** [comment]
It is possible to include lambdas in mustache context with 2 steps:
1. Add C++11 lambda support to `crow::json::wvalue` (possibly using `std::function`).
2. Have the mustache parser execute the lambda when found and put the result into the template.

Having `crow::json::rvalue` support templates (in order to fix point 3 in my previous comment) would require some way of parsing a string into code during runtime, which is less than possible considering C++ is compiled and runtime compilation (if possible) is a terrible idea. 
One way to avoid this is to use a special language that can be parsed into C++ during runtime. Although this solution would not be a C++ lambda implementation and would require developing a new interpreted language.

**Comment by The-EDev** [comment]
I was able to implement a C++11 lambda as a type in crow::json::wvalue. But when assigning it I have to use `jsonobj["key"] = std::function<std::string()>([](){return "Lambda works";});` because using `jsonobj["key"] = [](){return "Lambda works";};` returns an ambiguous operator (compiler does not know whether the value is boolean or lambda for some reason). @mrozigor should I keep the `std::function` part or do you have any idea on how to fix it?

**Comment by The-EDev** [comment]
Update: The most basic lambda tags (Interpolation test from `lambdas.yml`) have been implemented and is working. Moving on to work on the other features (expansion, sections (text argument), escaping, etc..)

**Comment by mrozigor** [comment]
I think wrapping in std::function is OK. But to be honest, after your spec summary I think implementing lambdas is a little bit redundant - you can just implement proper function to parse data and pass it to the template.

**Comment by The-EDev** [comment]
I think it's more of a convenience feature, I'll keep working on it for now since I got a basic version working.

**Comment by The-EDev** [comment]
I managed to get expansion working, basically if the context value is a lambda, execute it and get the string. Then if an instance of `{{` is found, treat the output as its own template and parse then render it using the same context provided. Otherwise move on and add the result to the output.

Only thing left is a few tests, an example, and a mention in the documentation.
