### ISSUE TITLE
Compilation fails on VisualStudio (windows)

### ISSUE THREAD

**Issue by kingster** [CrowCpp/Crow#370]
The upper case ENUM's are not defined in windows as the `DELETE` & `TRACE`  is already defined in `winnt.h`, which leads to compilation error
```
  GET, HEAD, POST, PUT, CONNECT, OPTIONS, TRACE, PATCH, PURGE, COPY, LOCK, MKCOL, MOVE, PROPFIND, PROPPATCH, SEARCH, UNLOCK, BIND, REBIND, UNBIND, ACL,
```

<img width="1244" alt="image" src="https://user-images.githubusercontent.com/709368/159237573-7e7646d0-dada-42e3-855d-26c489883822.png">

```
    enum class HTTPMethod : char
    {
#ifndef DELETE
        DELETE = 0,
```

<img width="1242" alt="image" src="https://user-images.githubusercontent.com/709368/159237691-b94a42f6-47fa-452f-88ab-c66efa7f0a2a.png">

@The-EDev given that the conflicts what should be the right way to handle this? 

- Switch to only lowercase & remove capitals
- Prefix the enum to avoid conflicts

**Comment by The-EDev** [comment]
I'm not sure what the problem here is. All caps methods are not available to Windows for the reason you mentioned so a developer will need to use `Get` `Post` `Delete` etc.. instead. 
On a unix based system it's optional but advised to still use the lowercase methods.
With the uppercase methods being kept because that's how they're represented for the most part.

**Comment by kingster** [comment]
The problem is that, even though I am in my code using the smaller ones, the compilation is failing because in lot of places the upper-cases is used which is undefined in case of windows.

**Comment by The-EDev** [comment]
hmmm, I'll upload a fix for that ASAP
