### ISSUE TITLE
Original header data as TCP buffer

### ISSUE THREAD

**Issue by akaoray** [CrowCpp/Crow#379]
Hello.

Is it possible to access the original request header, TCP request buffer. (Without ci_map where data stored in unordered_multimap with another order by hash)

I see class HTTPParser has methods on_header_field and on_header_value. Can they be intercepted? Or is it possible to get access to TCP request buffer and parsed these data yourself?

Thanks!

**Comment by akaoray** [comment]
This is needed for a specific task, like building a fingerprint based on the order of the keys in the headers (As part of anti-fraud system). Each application (Chrome, Mozilla, Safari etc) can have its own sequence of these parameters and you can calculate the fingerprint from this data.

**Comment by The-EDev** [comment]
you could probably use `on_header_field` for this case since it gets called every time the parser finds a header's key. I would add the sequence of keys or the fingerprint itself as a variable to the request, since that's the only way your handler can access data from the parser. Then you can either store the sequence and calculate the fingerprint in the handler (Route), or calculate the fingerprint in the parser itself.

**Comment by akaoray** [comment]
Thanks. This confirmed my thoughts on this matter, I think this solution will work.
