### ISSUE TITLE
Requesting a static file with an extension crow doens't know about causes an uncaught exception

### ISSUE THREAD

**Issue by danielskeenan** [CrowCpp/Crow#410]
Asking crow to respond to a static file request using `crow::response::set_static_file_info` causes an uncaught `std::out_of_range` exception if the file's extension is not one crow knows about (i.e. not in `crow::mime_types`).

**Comment by The-EDev** [comment]
I'm guessing this is for files without a `.` in their names (since that's how Crow determines the extension). The best fix would be to add an extension / mime-type argument to the method, while also adding an if statement [before here](https://github.com/CrowCpp/Crow/blob/db53bd619b51d4e45c03206adcb38eaf9683562a/include/crow/http_response.h#L244).

**Comment by danielskeenan** [comment]
This actually came up when Android Chrome requested `site.webmanifest`.  Working on a PR now to handle the std::out_of_range when setting the mime type.
