### ISSUE TITLE
Upagrade to Cpp17

### ISSUE THREAD

**Issue by Borwe** [CrowCpp/Crow#483]
I have to ask, why not upgrade to cpp17 atleast?

**Comment by The-EDev** [comment]
Primarily because switching means any C++11 library (like sqlpp11 for example) will no longer work with Crow. Not to mention many people who use Crow with an existing application use C++11, even QT only switched to C++11 very recently.

I currently don't believe that C++17 offers enough to overcome this fact.

I should also mention that Crow still works with C++17 and C++20. So practically upgrading would only drop compatibility without gaining any.

**Comment by autoantwort** [comment]
> Primarily because switching means any C++11 library (like sqlpp11 for example) will no longer work with Crow.  

sqlpp11 does not use crow.  

> QT only switched to C++11 very recently 

Qt switched to C++11 2016, 6 years before your post. And to C++17 2020, 2 years before your post.
