### ISSUE TITLE
Support for boost asio

### ISSUE THREAD

**Issue by nlyan** [CrowCpp/Crow#490]
Hi guys,

What's the story with 3a485078b85b61f1f49fb4466d5a7d350e155fc6? Is the Boost version of ASIO no longer going to be supported?

It would be preferable in my view, given that Boost is a dependency for so many code bases for other reasons, that the Boost flavor is still supported, otherwise you're just forcing an additional dependency on users.

**Comment by The-EDev** [comment]
Well The commit you're referencing is part of #482 which is a follow up to #457.

And while I wouldn't use the word support (since Crow is using, not supporting a dependency), yes, the idea is to get off of boost and use the standalone ASIO library instead.

I understand that since some people have boost, why bother installing ASIO. But there are also 2 other categories of people, one that doesn't have boost installed, and another that dislikes boost for being a massive package.

I would love to flip a switch and have both versions working, unfortunately if you look at #457, it is not at all the case.

**Comment by nlyan** [comment]
A lot of the deboostification is about migration to std:: so, makes a lot of sense.

However, Boost.ASIO and vanilla ASIO are virtually 100% compatible. It seems like the extra work in supporting both would be relatively minor, perhaps just shuffling some includes around, and adding some ifdef's or namespace aliases.

WebSocket++ does this here: https://github.com/zaphoyd/websocketpp/blob/1b11fd301531e6df35a6107c1e8665b1e77a2d8e/websocketpp/common/asio.hpp

Only supporting vanilla asio makes it much more difficult for Crow to share an io_context with other ASIO libraries (Boost Beast, RPC frameworks like [asio-grpc](https://github.com/Tradias/asio-grpc etc). It also means any future work on asynchronous handlers will be less useful (because you won't be able to compose asynchronous operations with host code using Boost.ASIO)

Looking at asio vanilla, at just one distro (Manjaro/Arch)

 - ASIO is stable at 1.20.x but Boost is stable at 1.79.x (which incorporates asio 1.22.x).
 - The Boost package is [used by 253](https://archlinux.org/packages/extra/x86_64/boost/)
 - The naked asio package is only used by [just 8 packages](https://archlinux.org/packages/extra/any/asio/)

**Comment by luca-schlecker** [comment]
As the author of the #457 and the follow-up #482 PR, I'll just throw in my opinion too.

I've generally disliked using Boost due to its sheer size. Asio is a part of it, but the rest just isn't needed for Crow, as it can just rely on standard features. That's why I made the push away from Boost as a dependency in favor of standalone Asio.

I agree with you that supporting both would be really cool though.
It doesn't feel like too much work to get both up and running. I'll take a look at it when I find the necessary time as there currently are other things I am working on, but it's on my list.

**Comment by TheQue42** [comment]
Trying to understand the above discussion, and sorry if this doesnt belong here, but the https://crowcpp.org/master/getting_started/setup/linux/ says nothing about boost is required, but I cant cmake/make without boost?

**Comment by xia-stan** [comment]
I belong in the camp that _doesn't_ have boost installed by default. The move to the standalone ASIO was great for me as I could drop 37 header dependencies from my project. One thing to note is that the ASIO Standalone (boost dependency free) may not be supported in the future. See chriskohlhoff/asio#1208. 

@TheQue42 : I ran into a similar problem in #585. If you're using HEAD then, you no longer need boost. You will need the [headers from the ASIO repo](https://github.com/chriskohlhoff/asio.git). When building make sure your compiler include path can find the headers, and pass the `-DASIO_STANDALONE` flag.

**Comment by 8188** [comment]
Thanks for xia-stan, I finally comiple helloworld example as 
`g++ helloworld.cpp -o helloworld -DASIO_STANDALONE -I..\include -ID:\asio-master\asio\include -lws2_32 -lwsock32`
on **windows10** with **mingw32**.

**Comment by jbulow** [comment]
Any update on this? Really unfortunate Crow can't be used with an existing code base already having boost as a dependency.

**Comment by gittiver** [comment]
No. Actually there are no plans to support boost, but if you need it, feel free to add a pull request containing support for boost::asio.
