### ISSUE TITLE
Add possibility to remove routes.

### ISSUE THREAD

**Issue by mrozigor** [CrowCpp/Crow#5]
In response to https://github.com/ipkn/crow/issues/367

**Comment by The-EDev** [comment]
I'm still not sure what removing routes means, does it mean removing them in real-time while the server is running? or something completely different.

**Comment by mrozigor** [comment]
I think that issue was to dynamically remove routes in response to some user action or application state, during runtime.

**Comment by The-EDev** [comment]
Well such a thing could easily be done with a middleware, you just have a list of _removed routes_, a function to remove a route (by adding it to the list), and have your `before_handle` return a 404 if the path matches a removed route, we can probably also use the existing route matching system, or `black_magic` to get the type of any variable in the user (things like `/endpoint/<int>`) in the URL.

Though I don't recall any web API (or webserver) that I know of dynamically removing an endpoint based on some action. But it's 2020 anything can happen :D

**Comment by The-EDev** [comment]
Crow stores all the rules in 2 data structures, a `vector` of rule object pointers, and a `Trie` for searching

The way a Trie works for crow (definitely look up Trie data structures before reading this) is it stores each character of a rule's URL in a tree node, with only the last character having a variable called a `rule_index`, the find algorithm is meant to go through a given URL char by char until the last node is reached, then the rule index from that node will be the one to correspond to where in the `vector` the rule (and its handler) is.

Crow's Trie does not have a "delete rule" method, Implementing such a method would require the following:
- Finding the rule in the trie.
- checking if the last node has any children.
- if it does, then only remove the `rule_index`.
- otherwise delete nodes one by one (from the leaf node up) until the first node with a `rule_index` or the haed node is reached.

**Comment by The-EDev** [comment]
closing this issue since I don't believe this feature should be added to Crow, @mrozigor please let me know if you disagree.

**Comment by nuno636** [comment]
The idea of removing a route makes perfect sense to me. We can add a blueprint at runtime, loading it from an external shared library, so we should be able to remove it too.
I just tried exactly this: creating a .dll with just a blueprint, load the .dll at runtime and register the blueprint. It works perfectly. Now, what if I want to unload this dll? With the dll blueprint registered I can't unload the library without a crash.
I agree, there should be a way to deregister a route.
