### ISSUE TITLE
I have two processes that must open a websocket using same ip and port, is that possible ? 

### ISSUE THREAD

**Issue by akjt** [CrowCpp/Crow#527]
So, in the end I want two processes (i.e. do not share memory) which opens a websocket at the same ip address and port number. The difference between the two is that they route different URLs. I have written a simple case here (although this runs on the same process and even same thread, but if that does not work than surely my initial plan won't):

```
int main() {
    std::string host = std::string("127.0.0.1");
    uint16_t port = 5280;
    crow::SimpleApp m_app1;
    crow::SimpleApp m_app2;
    std::future<void> m_async_thread_server1;
    std::future<void> m_async_thread_server2;


    CROW_ROUTE(m_app1, "/stream/data1")
        .websocket()
        .onaccept([](const crow::request& /*req*/){
            // Logic to accept a client.
            return true;
        })
        .onopen([&](crow::websocket::connection& /*conn*/){

        })
        .onclose([&](crow::websocket::connection& /*conn*/, const std::string& /*reason*/){

        });

    m_async_thread_server1 = m_app1
        .bindaddr(host)
        .port(port)
        .run_async();


    CROW_ROUTE(m_app2,  "/stream/data2")
        .websocket()
        .onaccept([](const crow::request& /*req*/){
            // Logic to accept a client.
            return true;
        })
        .onopen([&](crow::websocket::connection& /*conn*/){

        })
        .onclose([&](crow::websocket::connection& /*conn*/, const std::string& /*reason*/){

        });

    m_async_thread_server2 = m_app2
        .bindaddr(host)
        .port(port)
        .run_async();

    while (true){

    }

    return 0;
}

```

Currently, I cannot seem to make it work unless I change the port number of one of them? Is that type not possible in Crow at all ? 

While debugging I realized it somehow hangs at this call (the second time I try to create a websocket) :

`                 server_ = std::move(std::unique_ptr<server_t>(new server_t(this, bindaddr_, port_, server_name_, &middlewares_, concurrency_, timeout_, nullptr)));`

And exactly at this line inside the Server class:

`             acceptor_(io_service_, tcp::endpoint(boost::asio::ip::address::from_string(bindaddr), port)),
`

**Comment by MichaelSB** [comment]
This is not possible. Not only in crow, it's not possible at all. If you want 2 programs handling different routes, but using the same port when called from outside you have to use a proxy like nginx or some api-gateway. They would route different routes to the programs listening on different ports. What you want does not work, because the routing by request paths is done in the application layer. The network layer, handling ip/port does not know anything about it. It would not know, which packet has to go to which program. The network layer also does not care about protocols. It does not care, if the app uses http, smtp, xmpp..., so there is no way to do this before the packets hit the application.
