### ISSUE TITLE
Possible to provide prebuilt "crow_all.h" file.

### ISSUE THREAD

**Issue by baylf2000** [CrowCpp/crow#53]
As a Visual Studio user it seems to be beyond me to be able to build the "crow_all.h" file myself.

Is there any chance someone could provide this file here, as they used to do on the previous version of the project? It would be a huge help to those of us less competent.

If that's not feasible, then perhaps you could provide an simple example of how the "merge_all.py" script should be used, because right now it makes no sense to me.

Many thanks for all your efforts.

**Comment by The-EDev** [comment]
The `crow_all.h` file is provided with each release, though it might be a good idea to have it somewhere with every CI run (some form of a nightly build).

As for how to use `merge_all.py`, you need to call `python merge_all.py ../include crow_all.h`, although from what I've seen it seems the script is designed for linux (paths are separated by `/` instead of `\`).

I'll see if I can get it to work with windows, although any help with that regard is appreciated.

**Comment by mrozigor** [comment]
Maybe: https://stackoverflow.com/a/50738724/2568147

**Comment by The-EDev** [comment]
Applied the change, just gonna test it on a windows VM and make a PR

**Comment by The-EDev** [comment]
@baylf2000 I was able to run the script like this (please update to the latest commit on `master`):
1. open `cmd`
2. `cd where\crow\is\scripts`
3. `python merge_all.py ..\include crow_all.h`

This should generate the `crow_all.h` file in the same folder as `merge_all.py`

Note: I'm not sure if this works with python 2, I used python 3

**Comment by baylf2000** [comment]
Thank you, the built worked perfectly, and I also found the release version.
