### ISSUE TITLE
Drone build for PRs is hanging

### ISSUE THREAD

**Issue by gittiver** [CrowCpp/Crow#581]
Hi,

the drone build used as check on PR's seems to hang. 
See this Pul Request: https://github.com/CrowCpp/Crow/pull/580

**Comment by The-EDev** [comment]
I've been trying to figure out what's going wrong with this for a while now, I have no idea what's causing it...

**Comment by gittiver** [comment]
what about using GitHub actions for building, testing and generating gh pages?

**Comment by The-EDev** [comment]
I've looked at actions when travis changed their structure. I ultimately decided against it because of the point system and it being a closed source system that cannot be self hosted.

I've been looking into hosting drone myself, and I think it's doable. the only disadvantage is that ARM testing will have to be dropped for the time being I believe.

**Comment by gittiver** [comment]
drone.io is also changing into an at least only open core model. gh actions means always running checks without efforts to maintain the CI itself. 
I mean, there is a simple, small PR which seems blocked, because of not running checks/ problems with drone. 
The actions could be activated by a few configuration files and bam, there would be a proof that a changed PR is working.

I could provide adapted action for building in a PR, should I?

**Comment by The-EDev** [comment]
@gittiver Thanks a lot for adding github actions support to Crow! I'm guessing this issue should be closed now. Please let me know if it needs to stay open.

**Comment by gittiver** [comment]
No, can be closed. Only Windows build is not yet supported on GitHub actions. but this is a separate issue.
