### ISSUE TITLE
Update the Conan recipe

### ISSUE THREAD

**Issue by dertuxmalwieder** [CrowCpp/crow#62]
As this version is maintained and the ipkn version is not, could you push your fork to Conan one day?
It is not quite great to only have [the unmaintained version](https://conan.io/center/crow?tab=recipe) there.

**Comment by The-EDev** [comment]
Yes indeed, but I've noticed (and correct me if I'm wrong) that Conan and Conan center are 2 different things, since Crow had a conanfile.py since 2016, it was only added to Conan center back in October ([here](https://github.com/conan-io/conan-center-index/issues/3064) and [here](https://github.com/conan-io/conan-center-index/pull/3123)), so I believe the correct course of action would be as follows:
1. Add the conanfile.py again (with updated data).
2. contact the people behind the Issue and PR and ask them to possibly change the URL to this repository as opposed to the unmaintained one.

**Comment by The-EDev** [comment]
https://conan.io/center/crowcpp-crow
