### ISSUE TITLE
Type Conversion

### ISSUE THREAD

**Issue by ahertlcode** [CrowCpp/Crow#652]
Is there away to convert between crow::json::wvalue and crow::json::rvalue vice versa? It  would be very useful and hand for my purpose. I have gone through the documentation but couldn't seem to get a straight forward guide on this. Thank you.

**Comment by The-EDev** [comment]
`rvalue`s are supposed to used to read json strings, you can create a `wvalue` using an `rvalue` if you want to edit your JSON. although it doesn't work the other way around since `rvalue` is intended to be read-only. There were some plans to get rid of `rvalue` and just have a unified json value. But someone needs to implement that.
