### ISSUE TITLE
Possible make install rule for cmake ?

### ISSUE THREAD

**Issue by GuacheSuede** [CrowCpp/crow#68]

**Comment by The-EDev** [comment]
Well Crow is a header only library, meaning there isn't anything to compile, you just copy the header file(s) into your project and include it/them.

If I'm getting this completely wrong I apologize and could you please clarify how an install rule could be useful?

**Comment by GuacheSuede** [comment]
What i do is copy the crow headers into /usr/include manually via `cp` so that i can be used globally. Would be good to have a make install step that does this automatically

**Comment by The-EDev** [comment]
Hmmm, I understand now, I'll look into it when I can (I'm focusing on Documentation at the moment), If you have time and don't mind doing it, feel free to open a PR and I'll merge it.

**Comment by GuacheSuede** [comment]
Understood.

I have a question.  I performed some benchmarks on Crow and realized that it seems after the first initial connection, responses to requests are retuned very fast. Would you know which part of the code allows this to happen ? 

Thanks.

**Comment by The-EDev** [comment]
I'm assuming that you're using different routes, this is most likely due to crow having to initialize some ASIO objects that are then being reused, though I'm not sure which objects these are, you can look in `http_server.h` (`do_accept()`) and `http_connection.h` if you'd like to investigate this further.

if you're using the same request on a browser, it's most likely the browser itself caching the result.

**Comment by ayaankhan98** [comment]
Is it fine to write a bash script to automate this process of installation (basically copying to `/usr/include`) after successful local build

**Comment by The-EDev** [comment]
Why do that when cmake can have a specific install rule?

**Comment by ayaankhan98** [comment]
> Why do that when cmake can have a specific install rule?

yes will do that with cmake Install rules; don't know why i had mentioned about bash script.
