### ISSUE TITLE
Is the Crow framework  production-ready? I mean if I combine it with additional libraries, will it be ok for production?

### ISSUE THREAD

**Issue by hyphypnotic** [CrowCpp/Crow#813]
Is the Crow framework  production-ready? I mean if I combine it with additional libraries, will it be ok for production?

**Comment by InternalHigh** [comment]
Dear @hyphypnotic I found the following info from the ex-maintainer:

![image](https://github.com/CrowCpp/Crow/assets/3605191/323be30b-6605-4f9d-9ec3-15ea5ec0fdd1)

**Comment by gittiver** [comment]
putting behind Apache or nginx is for using their security related modules to protect against some attacks.
 
I would currently also consider the https implementation as test only, but this could be also be handled by having it behind a reverse proxy.

**Comment by witcherofthorns** [comment]
> Is the Crow framework production-ready? I mean if I combine it with additional libraries, will it be ok for production?

I don't quite understand your question, but if we are talking about sharing Crow with other libraries, then yes, it works quite well. Let's say I use Crow together with MongoDB, RabbitMQ, Memcache, Jwt, json nlohmann, everything works as it should. Yes, of course, you need to remember that most of these libraries use blocking calls, so you will have to take care of this, it is possible to initially allocate a separate execution thread for RabbitMQ for example. For my convenience, I wrote small wrappers for each of the libraries and that’s it, to simplify working with them, they are all used thanks to the Conan package manager and CMake, and that’s it

At the moment I am developing a project using Crow, and everything seems to be going as it should, I am using a small micro-service architecture with the ability to expand if necessary, and I also use caching, this is completely enough, in fact, most of my requests work through RabbitMQ asynchronously together with Websocket (for frontend app), as the application requires it. Yes, Crow still has some minor problems, but I think they can all be solved with time

In general and in general, if you follow the general rules for building a backend application and design patterns, then it won’t make much difference what you use, be it Python, Java, C# web frameworks, besides no one is stopping you from wrapping your application in a Docker container and use some kind of CI/CD

The main point of Crow is that you have almost nothing, only basic things, if you need something else, you implement it, and I think this is a big plus, since I personally don’t like it when frameworks have a lot of garbage - which I don't need its at all
